Repository fluxcd/pkg, pull requests merged in 2021-12, with the labels that each got.

#192 ssa: Force apply on invalid and conflict errors
  ssa/manager_apply_test.go
  ssa/testdata/test1.yaml
  ssa/utils.go
Labels: bug, area/server-side-apply

#193 ssa: Remove YAML diff
  ssa/changeset.go
  ssa/manager_diff.go
  ssa/manager_diff_test.go
Labels: area/server-side-apply

#194 ssa: Allow consumers to override the apply order
  ssa/sort.go
Labels: area/server-side-apply

#195 ssa: Fix apply order override
  ssa/sort.go
Labels: area/server-side-apply

#177 Run build in container
  .github/actions/run-tests/Dockerfile
  .github/actions/run-tests/action.yml
  .github/workflows/build.yaml
Labels: area/actions
