Repository fluxcd/pkg, pull requests merged in 2022-05, with the labels that each got.

#266 Add WithSSHConfig and PublicKeyLookupFunc
  gittestserver/go.mod
  gittestserver/go.sum
  gittestserver/server.go
Labels: area/testserver

#271 runtime: Add Feature Gates
  runtime/features/features.go
  runtime/features/features_test.go
  runtime/go.mod
  runtime/go.sum
Labels: enhancement, area/runtime

#270 runtime: Use server-side throttling when available
  runtime/client/client.go
  runtime/go.mod
  runtime/go.sum
Labels: area/runtime

#272 Update dependencies
  .github/actions/run-tests/Dockerfile
  .github/workflows/actions.yaml
  apis/kustomize/go.mod
  apis/kustomize/go.sum
  apis/meta/go.mod
  apis/meta/go.sum
  kustomize/go.mod
  kustomize/go.sum
  runtime/go.mod
  runtime/go.sum
  ssa/go.mod
  ssa/go.sum
Labels: area/build

#278 Update helm to v3.9.0
  helmtestserver/go.mod
  helmtestserver/go.sum
Labels: dependencies

#279 Update go-yaml to v3.0.0
  apis/kustomize/go.mod
  apis/kustomize/go.sum
  apis/meta/go.mod
  apis/meta/go.sum
  gittestserver/go.mod
  gittestserver/go.sum
  helmtestserver/go.mod
  helmtestserver/go.sum
  runtime/go.mod
  runtime/go.sum
  ssa/go.mod
  ssa/go.sum
Labels: dependencies

#280 kustomize: Update go-yaml to v3.0.0
  kustomize/go.mod
  kustomize/go.sum
Labels: dependencies

#281 Add OSSF Scorecards action
  .github/workflows/actions.yaml
  .github/workflows/build.yaml
  .github/workflows/cifuzz.yaml
  .github/workflows/ossf.yaml
  .github/workflows/scan.yaml
Labels: area/actions

#282 Add tests for `ParseKnownHosts` and `KnownKey.Matches`
  ssh/knownhosts/known_key_test.go
Labels: area/git

#283 Update internal dependencies
  kustomize/go.mod
  runtime/go.mod
Labels: area/build

#285 ssh: Enforce ClientConfig default values
  ssh/host_key.go
Labels: bug, area/git
