Repository fluxcd/pkg, pull requests merged in 2023-11, with the labels that each got.

#682 oci/tests/int: Set exit code 1 on tf destroy fail
  oci/tests/integration/suite_test.go
Labels: area/testing

#681 *: change default permissions
  helmtestserver/server.go
  kustomize/filesys/fs_secure_test.go
  oci/client/internal/fs/fs_test.go
  tar/tar.go
  tar/tar_test.go
  testserver/artifact.go
Labels: enhancement

#675 [oci] Extend oci.Push to create layer with static uncompressed contents
  oci/client/build.go
  oci/client/build_test.go
  oci/client/diff.go
  oci/client/diff_test.go
  oci/client/pull_test.go
  oci/client/push.go
  oci/client/push_pull_test.go
  oci/globals.go
Labels: enhancement, area/oci

#671 runtime/controller: add error type for insecure HTTP connections
  runtime/controller/connection.go
  runtime/controller/connection_test.go
Labels: enhancement, area/runtime

#686 Update to Kubernetes v2.28 and Kustomize v5.2
  apis/event/go.mod
  apis/event/go.sum
  apis/kustomize/go.mod
  apis/kustomize/go.sum
  apis/meta/go.mod
  apis/meta/go.sum
  git/gogit/go.mod
  git/gogit/go.sum
  git/internal/e2e/go.mod
  git/internal/e2e/go.sum
  helmtestserver/go.mod
  helmtestserver/go.sum
  kustomize/go.mod
  kustomize/go.sum
  oci/go.mod
  oci/go.sum
  oci/tests/integration/go.mod
  oci/tests/integration/go.sum
  runtime/client/client.go
  runtime/client/impersonator.go
  runtime/go.mod
  runtime/go.sum
  runtime/pprof/pprof.go
  runtime/testenv/testenv.go
  ssa/changeset.go
  ssa/go.mod
  ssa/go.sum
  ssa/main_test.go
  ssa/manager.go
  ssa/manager_wait.go
  ssa/manager_wait_test.go
  ssa/sort.go
  ssa/utils.go
  ssh/go.mod
  ssh/go.sum
Labels: dependencies

#687 Update internal dependencies
  git/gogit/go.mod
  git/gogit/go.sum
  git/internal/e2e/go.mod
  git/internal/e2e/go.sum
  kustomize/go.mod
  runtime/go.mod
  runtime/go.sum
Labels: dependencies

#692 ssa: prevent unnecessary `DeepCopy`
  ssa/manager_apply.go
  ssa/manager_delete.go
  ssa/manager_diff.go
Labels: area/server-side-apply

#693 Update go-git to v5.10.1
  git/gogit/go.mod
  git/gogit/go.sum
  git/internal/e2e/go.mod
  git/internal/e2e/go.sum
Labels: dependencies, area/git

#694 Use `gomega` in sourceignore package
  git/go.mod
  git/go.sum
  git/gogit/go.mod
  git/gogit/go.sum
  git/internal/e2e/go.mod
  git/internal/e2e/go.sum
  gittestserver/go.mod
  gittestserver/go.sum
  http/fetch/go.mod
  http/fetch/go.sum
  kustomize/go.mod
  kustomize/go.sum
  oci/go.mod
  oci/go.sum
  oci/tests/integration/go.mod
  oci/tests/integration/go.sum
  sourceignore/go.mod
  sourceignore/go.sum
  sourceignore/sourceignore_test.go
  ssh/go.mod
  ssh/go.sum
Labels: dependencies

#695 Update internal dependencies
  git/gogit/go.mod
  git/internal/e2e/go.mod
  kustomize/go.mod
  oci/go.mod
Labels: dependencies
