Repository fluxcd/pkg, pull requests merged in 2024-04, with the labels that each got.

#750 Update dependencies to Go 1.22 and Kubernetes 1.29.3
  .github/workflows/build.yaml
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/integration-azure.yaml
  .github/workflows/integration-cleanup.yaml
  .github/workflows/integration-gcp.yaml
  .github/workflows/scan.yaml
  Makefile
  apis/acl/go.mod
  apis/acl/zz_generated.deepcopy.go
  apis/event/go.mod
  apis/event/go.sum
  apis/event/v1beta1/zz_generated.deepcopy.go
  apis/kustomize/go.mod
  apis/kustomize/go.sum
  apis/kustomize/zz_generated.deepcopy.go
  apis/meta/go.mod
  apis/meta/go.sum
  apis/meta/zz_generated.deepcopy.go
  git/go.mod
  git/go.sum
  git/gogit/go.mod
  git/gogit/go.sum
  git/internal/e2e/go.mod
  git/internal/e2e/go.sum
  gittestserver/go.mod
  gittestserver/go.sum
  helmtestserver/go.mod
  helmtestserver/go.sum
  http/fetch/go.mod
  http/fetch/go.sum
  http/transport/go.mod
  kustomize/go.mod
  kustomize/go.sum
  lockedfile/go.mod
  masktoken/go.mod
  oci/go.mod
  oci/go.sum
  oci/tests/integration/go.mod
  oci/tests/integration/go.sum
  runtime/go.mod
  runtime/go.sum
  sourceignore/go.mod
  sourceignore/go.sum
  ssa/go.mod
  ssa/go.sum
  ssh/go.mod
  ssh/go.sum
  tar/go.mod
  tests/fuzz/Dockerfile.builder
  testserver/go.mod
  version/go.mod
Labels: dependencies

#754 Update docker dependencies
  helmtestserver/go.mod
  helmtestserver/go.sum
  oci/go.mod
  oci/go.sum
  oci/tests/integration/go.mod
  oci/tests/integration/go.sum
Labels: dependencies

#752 Return a DiffTypeExclude when exclusion annotation is set in cluster
  ssa/jsondiff/unstructured.go
  ssa/jsondiff/unstructured_test.go
Labels: enhancement, area/server-side-apply

#755 Update internal dependencies
  git/gogit/go.mod
  git/gogit/go.sum
  git/internal/e2e/go.mod
  git/internal/e2e/go.sum
  helmtestserver/go.mod
  http/fetch/go.mod
  kustomize/go.mod
  oci/go.mod
  oci/go.sum
  oci/tests/integration/go.mod
  oci/tests/integration/go.sum
  runtime/go.mod
Labels: dependencies

#756 Update dependencies to Kustomize v5.4.0
  kustomize/go.mod
  kustomize/go.sum
  runtime/go.mod
  runtime/go.sum
  ssa/go.mod
  ssa/go.sum
Labels: dependencies

#757 kustomize: Allow empty resources in `kustomization.yaml`
  kustomize/filters.go
  kustomize/kustomize_generator.go
  kustomize/kustomize_generator_test.go
  kustomize/testdata/noResources/ks.yaml
  kustomize/testdata/noResources/kustomization.yaml
Labels: area/kustomize

#758 Add envsubst package
  envsubst/README.md
  envsubst/doc.go
  envsubst/eval.go
  envsubst/eval_test.go
  envsubst/funcs.go
  envsubst/funcs_test.go
  envsubst/go.mod
  envsubst/go.sum
  envsubst/parse/node.go
  envsubst/parse/parse.go
  envsubst/parse/parse_test.go
  envsubst/parse/scan.go
  envsubst/path/match.go
  envsubst/template.go
Labels: area/envsubst

#759 kustomize: Implement envsubst strict mode
  kustomize/go.mod
  kustomize/go.sum
  kustomize/kustomize_varsub.go
  kustomize/kustomize_varsub_test.go
  kustomize/testdata/varsubstrict/config.yaml
  kustomize/testdata/varsubstrict/kustomization.yml
Labels: area/kustomize, area/envsubst

#761 kustomize: Add support for `namePrefix` and `nameSuffix`
  kustomize/kustomize_generator.go
  kustomize/kustomize_generator_test.go
  kustomize/testdata/name/ks.yaml
  kustomize/testdata/name/kustomization.yaml
Labels: area/kustomize

#763 Update dependencies to Kubernetes 1.30 and adapt to breaking changes
  Makefile
  apis/acl/go.mod
  apis/event/go.mod
  apis/event/go.sum
  apis/kustomize/go.mod
  apis/kustomize/go.sum
  apis/meta/go.mod
  apis/meta/go.sum
  envsubst/go.mod
  git/go.mod
  git/go.sum
  git/gogit/go.mod
  git/gogit/go.sum
  git/internal/e2e/go.mod
  git/internal/e2e/go.sum
  gittestserver/go.mod
  gittestserver/go.sum
  helmtestserver/go.mod
  helmtestserver/go.sum
  http/fetch/go.mod
  http/fetch/go.sum
  http/transport/go.mod
  kustomize/go.mod
  kustomize/go.sum
  lockedfile/go.mod
  masktoken/go.mod
  oci/go.mod
  oci/go.sum
  oci/tests/integration/go.mod
  oci/tests/integration/go.sum
  runtime/go.mod
  runtime/go.sum
  sourceignore/go.mod
  sourceignore/go.sum
  ssa/go.mod
  ssa/go.sum
  ssh/go.mod
  ssh/go.sum
  tar/go.mod
  testserver/go.mod
  version/go.mod
Labels: dependencies

#767 Update internal dependencies
  git/gogit/go.mod
  git/gogit/go.sum
  git/internal/e2e/go.mod
  git/internal/e2e/go.sum
  helmtestserver/go.mod
  http/fetch/go.mod
  http/fetch/go.sum
  kustomize/go.mod
  kustomize/go.sum
  oci/go.mod
  oci/go.sum
  oci/tests/integration/go.mod
  oci/tests/integration/go.sum
  runtime/go.mod
Labels: dependencies
