Repository fluxcd/pkg, pull requests merged in 2024-12, with the labels that each got.

#818 [RFC-007] Implement GitHub app authentication for git repositories.
  .github/workflows/e2e.yaml
  auth/github/client.go
  auth/github/client_test.go
  auth/go.mod
  auth/go.sum
  git/credentials.go
  git/credentials_test.go
  git/go.mod
  git/go.sum
  git/gogit/client.go
  git/gogit/client_test.go
  git/gogit/go.mod
  git/gogit/go.sum
  git/internal/e2e/README.md
  git/internal/e2e/github_test.go
  git/internal/e2e/go.mod
  git/internal/e2e/go.sum
  git/options.go
  oci/tests/integration/go.mod
  oci/tests/integration/go.sum
Labels: area/git

#828 Update dependencies
  apis/acl/go.mod
  apis/event/go.mod
  apis/kustomize/go.mod
  apis/meta/go.mod
  auth/doc.go
  auth/go.mod
  auth/go.sum
  cache/go.mod
  cache/go.sum
  envsubst/go.mod
  git/go.mod
  git/go.sum
  git/gogit/go.mod
  git/gogit/go.sum
  git/internal/e2e/go.mod
  git/internal/e2e/go.sum
  gittestserver/go.mod
  helmtestserver/go.mod
  http/fetch/go.mod
  http/transport/go.mod
  kustomize/go.mod
  kustomize/go.sum
  lockedfile/go.mod
  masktoken/go.mod
  oci/go.mod
  oci/go.sum
  oci/tests/integration/go.mod
  oci/tests/integration/go.sum
  runtime/go.mod
  runtime/go.sum
  sourceignore/go.mod
  ssa/go.mod
  ssa/go.sum
  ssh/go.mod
  tar/go.mod
  testserver/go.mod
  version/go.mod
Labels: dependencies

#830 Update internal dependencies
  git/go.mod
  git/go.sum
  git/gogit/go.mod
  git/gogit/go.sum
  git/internal/e2e/go.mod
  git/internal/e2e/go.sum
  http/fetch/go.mod
  http/fetch/go.sum
  kustomize/go.mod
  oci/go.mod
  oci/go.sum
  oci/tests/integration/go.mod
  oci/tests/integration/go.sum
  runtime/go.mod
  runtime/go.sum
  ssa/go.mod
  ssa/go.sum
  tar/go.mod
  tar/go.sum
  version/go.mod
  version/go.sum
Labels: dependencies

#831 Update internal Git dependencies
  git/gogit/go.mod
  git/internal/e2e/go.mod
  oci/go.mod
  oci/go.sum
  oci/tests/integration/go.mod
  oci/tests/integration/go.sum
Labels: dependencies

#836 Add `chartutil` package and `ValuesReference` type to APIs
  apis/meta/reference_types.go
  apis/meta/zz_generated.deepcopy.go
  chartutil/digest.go
  chartutil/digest_test.go
  chartutil/encode.go
  chartutil/encode_test.go
  chartutil/go.mod
  chartutil/go.sum
  chartutil/merge.go
  chartutil/merge_test.go
  chartutil/sort.go
  chartutil/sort_test.go
  chartutil/testdata/values.yaml
  chartutil/values.go
  chartutil/values_fuzz_test.go
  chartutil/values_test.go
Labels: area/api

#838 Update apis/meta version in chartutil and runtime
  chartutil/go.mod
  runtime/go.mod
Labels: dependencies

#839 workflows: Use setup-terraform install latest
  .github/workflows/integration-aws.yaml
  .github/workflows/integration-azure.yaml
  .github/workflows/integration-gcp.yaml
Labels: area/ci

#841 Make the variables loading function public
  kustomize/kustomize_varsub.go
Labels: area/kustomize

#842 Update dependencies to Kubernetes 1.32.0 and Go 1.23.0
  Makefile
  apis/acl/go.mod
  apis/acl/zz_generated.deepcopy.go
  apis/event/go.mod
  apis/event/go.sum
  apis/event/v1beta1/zz_generated.deepcopy.go
  apis/kustomize/go.mod
  apis/kustomize/go.sum
  apis/kustomize/zz_generated.deepcopy.go
  apis/meta/go.mod
  apis/meta/go.sum
  apis/meta/zz_generated.deepcopy.go
  auth/go.mod
  auth/go.sum
  cache/go.mod
  cache/go.sum
  chartutil/go.mod
  chartutil/go.sum
  envsubst/go.mod
  git/go.mod
  git/go.sum
  git/gogit/go.mod
  git/gogit/go.sum
  git/internal/e2e/go.mod
  git/internal/e2e/go.sum
  gittestserver/go.mod
  gittestserver/go.sum
  hack/boilerplate.go.txt
  helmtestserver/go.mod
  helmtestserver/go.sum
  http/fetch/go.mod
  http/fetch/go.sum
  kustomize/go.mod
  kustomize/go.sum
  lockedfile/go.mod
  masktoken/go.mod
  oci/go.mod
  oci/go.sum
  oci/tests/integration/go.mod
  oci/tests/integration/go.sum
  runtime/go.mod
  runtime/go.sum
  sourceignore/go.mod
  sourceignore/go.sum
  ssa/go.mod
  ssa/go.sum
  ssh/go.mod
  ssh/go.sum
  tar/go.mod
  testserver/go.mod
  version/go.mod
Labels: dependencies

#843 Update internal dependencies
  auth/go.mod
  chartutil/go.mod
  git/go.mod
  git/gogit/go.mod
  git/internal/e2e/github_test.go
  git/internal/e2e/go.mod
  git/internal/e2e/go.sum
  helmtestserver/go.mod
  http/fetch/go.mod
  kustomize/go.mod
  oci/go.mod
  oci/tests/integration/go.mod
  oci/tests/integration/go.sum
  runtime/go.mod
Labels: dependencies

#846 Add event recorder constructor decoupled from runtime Manager
  runtime/events/recorder.go
Labels: area/runtime
