Repository fluxcd/pkg, pull requests merged in 2025-08, with the labels that each got.

#1003 auth: add 10-second timeout to HTTP client for token acquisition
  auth/options.go
  auth/options_test.go
  oci/tests/integration/go.mod
Labels: area/security

#1008 [RFC-0010] auth: add lockdown support for multi-tenant workload identity
  auth/access_token.go
  auth/access_token_test.go
  auth/controller_flags.go
  auth/controller_flags_test.go
  auth/feature_gates.go
  auth/generic/provider_test.go
  auth/options.go
  auth/options_test.go
  auth/registry.go
  auth/registry_test.go
  auth/restconfig.go
  auth/restconfig_test.go
  auth/utils/restconfig.go
  oci/tests/integration/go.mod
  oci/tests/integration/testapp/main.go
Labels: enhancement, area/security

#1009 auth: eliminate unreasonable use of env vars
  auth/access_token_test.go
  auth/controller_flags.go
  auth/controller_flags_test.go
  auth/feature_gates.go
  auth/generic/provider_test.go
  auth/options.go
  auth/options_test.go
  auth/registry_test.go
  auth/restconfig_test.go
  oci/tests/integration/go.mod
Labels: hold, area/security

#1010 tests: move testdata and integration tests to tests
  .github/workflows/integration-aws.yaml
  .github/workflows/integration-azure.yaml
  .github/workflows/integration-gcp.yaml
  cmd/internal/test_modules.go
  docs/internal/release.md
  git/gogit/go.mod
  git/internal/e2e/go.mod
  gittestserver/server_test.go
  helmtestserver/go.mod
  http/fetch/go.mod
  tests/integration/.env.sample
  tests/integration/.gitignore
  tests/integration/Dockerfile
  tests/integration/Makefile
  tests/integration/README.md
  tests/integration/aws_test.go
  tests/integration/azure_test.go
  tests/integration/gcp_test.go
  tests/integration/git_test.go
  tests/integration/go.mod
  tests/integration/go.sum
  tests/integration/job_test.go
  tests/integration/oci_test.go
  tests/integration/restconfig_test.go
  tests/integration/suite_test.go
  tests/integration/terraform/aws/main.tf
  tests/integration/terraform/aws/oidc_assume_role_policy.json
  tests/integration/terraform/aws/outputs.tf
  tests/integration/terraform/aws/variables.tf
  tests/integration/terraform/azure/main.tf
  tests/integration/terraform/azure/outputs.tf
  tests/integration/terraform/azure/variables.tf
  tests/integration/terraform/azure/version.tf
  tests/integration/terraform/gcp/main.tf
  tests/integration/terraform/gcp/outputs.tf
  tests/integration/terraform/gcp/variables.tf
  tests/integration/testapp/main.go
  tests/integration/util_test.go
  tests/testdata/certs/Makefile
  tests/testdata/certs/ca-config.json
  tests/testdata/certs/ca-csr.json
  tests/testdata/certs/ca-key.pem
  tests/testdata/certs/ca.csr
  tests/testdata/certs/ca.pem
  tests/testdata/certs/server-csr.json
  tests/testdata/certs/server-key.pem
  tests/testdata/certs/server.csr
  tests/testdata/certs/server.pem
  testserver/http_test.go
Labels: area/testserver, area/testing

#1013 meta: Add `History` API for tracking reconcile runs in status
  apis/meta/history.go
  apis/meta/history_test.go
  apis/meta/zz_generated.deepcopy.go
  auth/go.mod
  chartutil/go.mod
  helmtestserver/go.mod
  helmtestserver/go.sum
  runtime/go.mod
  tests/integration/go.mod
Labels: area/api
