Repository fluxcd/pkg, pull requests merged in 2025-05, with the labels that each got.

#923 ssa: Implement `WaitForSetTermination`
  ssa/changeset.go
  ssa/manager_wait.go
  ssa/manager_wait_test.go
Labels: enhancement, area/server-side-apply

#924 [RFC-0010] Add integration tests for object-level workload identity
  .github/workflows/integration-aws.yaml
  .github/workflows/integration-azure.yaml
  .github/workflows/integration-gcp.yaml
  oci/tests/integration/.env.sample
  oci/tests/integration/README.md
  oci/tests/integration/azure_test.go
  oci/tests/integration/git_test.go
  oci/tests/integration/go.mod
  oci/tests/integration/job_test.go
  oci/tests/integration/oci_test.go
  oci/tests/integration/suite_test.go
  oci/tests/integration/terraform/aws/variables.tf
  oci/tests/integration/terraform/azure/main.tf
  oci/tests/integration/terraform/azure/outputs.tf
  oci/tests/integration/terraform/azure/variables.tf
  oci/tests/integration/terraform/gcp/main.tf
  oci/tests/integration/terraform/gcp/variables.tf
  oci/tests/integration/testapp/main.go
Labels: area/testing

#925 [RFC-0010] Support cross-cloud object-level workload identity
  .github/workflows/integration-cleanup.yaml
  auth/aws/provider.go
  auth/aws/provider_test.go
  auth/azure/provider.go
  auth/azure/provider_test.go
  auth/gcp/gke_metadata_test.go
  auth/gcp/options.go
  auth/gcp/provider.go
  auth/gcp/provider_test.go
  auth/get_token.go
  auth/get_token_test.go
  auth/provider.go
  git/go.mod
  git/gogit/go.mod
  git/internal/e2e/go.mod
  oci/go.mod
  oci/tests/integration/go.mod
Labels: area/security

#927 [RFC-0010] Introduce feature gate for enabling object-level workload identity
  apis/meta/conditions.go
  auth/feature_gate.go
  auth/get_token.go
  auth/get_token_test.go
  oci/tests/integration/testapp/main.go
Labels: area/security

#930 Update controller-runtime to v0.21.0
  auth/go.mod
  auth/go.sum
  chartutil/go.mod
  chartutil/go.sum
  kustomize/go.mod
  kustomize/go.sum
  oci/tests/integration/go.mod
  oci/tests/integration/go.sum
  runtime/go.mod
  runtime/go.sum
  ssa/go.mod
  ssa/go.sum
Labels: dependencies

#931 Update helm to v3.18.0
  chartutil/go.mod
  chartutil/go.sum
  helmtestserver/go.mod
  helmtestserver/go.sum
Labels: dependencies
